server:
  port: 8085

api:
  finnhub:
    domain: 'finnhub.io'
    endpoint: "/api/v1"
    pathSegment: "stock"
    pathSegment2: "profile2"
    symbol: "AAPL"
    token:  "cju3it9r01qr958213c0cju3it9r01qr958213cg"

