server.port: 8085

api:
  finnhub:
    token: "cju3it9r01qr958213c0cju3it9r01qr958213cg"
    domain: "finnhub.io"
    base-url: "api/v1"
    endpoints:
      stock:
        stocksymbol: /stock/symbol
        profile2: "/stock/profile2"
        quote: "/quote"
# HTTPS://finnhub.io/api/v1/stock?exchange=US&token=cju3it9r01qr958213c0cju3it9r01qr958213cg


# real : 
# https://finnhub.io/api/v1/stock/symbol?exchange=US&token=cju3it9r01qr958213c0cju3it9r01qr958213cg

# JDBC連接
# Data Source Settings
spring.datasource:
    url: jdbc:mysql://localhost:3306/finnhub
    usersname: oscarlo
    password: oscarVenturenixLab2023.
    driver-class-name: com.mysql.cj.jdbc.Driver
spring.jpa:
  show-sql: true
   # optional to under "properties"
  properties:hibernate.dialect: org.hibernate.dialect.MySQLDialect
      # Either to use hibernate or spring.sql.init, otherwise it duplicated to create tables
  hibernate.ddl-auto:  create-drop # create, create-drop, update, none, validate
spring.sql.init:
      #   init:
      #    schema-locations: classpath:ddl/finnhub_stock_price.sql ,
      #                      classpath:ddl/FINNHUB_STOCK.sql
  mode: always # always
