server:
  port: 8085

api:
  finnhub:  
    domain: 'finnhub.io'
    endpoint: "/api/v1"
    profile:
      pathSegment: "stock"
      pathSegment2: "profile2"
    quote:
      pathSegment: "quote"    
    token:  "cju3it9r01qr958213c0cju3it9r01qr958213cg"
