server:
  port: 8089

spring.datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/finnhub
  usersname: oscarlo
  password: oscarVenturenixLab2023.
spring.jpa:
  show-sql: true
  hibernate.ddl-auto:
    update 
spring.sql.init:
  mode: always # always
  platform: mysql
spring.profiles.active: enableScheduling
